import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import type { PoolClient } from 'pg';
import type { EconomyRepository } from './economy.ts';
import { COMMUNITY_LIMITS as LIMITS, BRIDGEMIND_TWITCH_CHANNEL, communityImages, type CommunitySubmission, type Programme, type ProgrammeSettings } from '../../shared/community.ts';
export class CommunityError extends Error { constructor(message:string,readonly status=400){super(message);} }
const columns='id,title,credit,status,width,height,featured,sort_order,created_at';
function submission(row:any):CommunitySubmission{return {id:row.id,title:row.title,credit:row.credit,status:row.status,width:row.width,height:row.height,featured:row.featured,sortOrder:row.sort_order,createdAt:row.created_at.toISOString(),imageUrl:`/game/api/community/submissions/${row.id}/image`};}
export class CommunityRepository {
 constructor(readonly economy:EconomyRepository){}
 async initialise(){await this.economy.transaction(async c=>{await c.query('SELECT pg_advisory_xact_lock(782641092)');const versions=(await c.query('SELECT version FROM guest_schema_migrations')).rows.map(r=>r.version);if(!versions.includes(6)||versions.some(v=>![1,2,3,4,5,6,7,8,9,10].includes(v)))throw new Error('Unsupported community schema');if(!versions.includes(8)){await c.query(await readFile(new URL('./migrations/008_community.sql',import.meta.url),'utf8'));await c.query('INSERT INTO guest_schema_migrations(version) VALUES(8)');}});}
 private async lock(c:PoolClient){await c.query('SELECT singleton FROM community_programme WHERE singleton FOR UPDATE');}
 private async bump(c:PoolClient){await c.query('UPDATE community_programme SET revision=revision+1,epoch=clock_timestamp() WHERE singleton');}
 async programme():Promise<Programme>{return this.economy.transaction(async c=>{await this.lock(c);return this.snapshot(c);});}
 private async snapshot(c:PoolClient):Promise<Programme>{const row=(await c.query('SELECT *,clock_timestamp() AS server_now FROM community_programme WHERE singleton')).rows[0];const images=(await c.query(`SELECT ${columns} FROM community_images WHERE status='approved' ORDER BY featured DESC,sort_order,created_at,id`)).rows.map(r=>{const {status,createdAt,...image}=submission(r);return {...image,imageUrl:`/game/api/community/images/${r.id}`};});return {revision:row.revision,epochMs:row.epoch.getTime(),serverNowMs:row.server_now.getTime(),mode:row.mode,platform:row.platform,twitchChannel:BRIDGEMIND_TWITCH_CHANNEL,youtubeVideoId:row.youtube_video_id,schedule:row.schedule,images:communityImages(images)};}
 async list(owner?:string):Promise<CommunitySubmission[]>{return (await this.economy.pool.query(`SELECT ${columns} FROM community_images ${owner?'WHERE owner_id=$1':''} ORDER BY created_at DESC,id LIMIT 200`,owner?[owner]:[])).rows.map(submission);}
 async image(id:string,access:{public?:boolean;owner?:string;admin?:boolean}):Promise<Buffer|undefined>{return (await this.economy.pool.query(`SELECT image FROM community_images WHERE id=$1 AND ${access.public?"status='approved'":access.admin?'true':'owner_id=$2'}`,access.public||access.admin?[id]:[id,access.owner??null])).rows[0]?.image;}
 async submit(owner:string|null,title:string,credit:string,image:Buffer,width:number,height:number):Promise<CommunitySubmission>{return this.economy.transaction(async c=>{
  await this.lock(c);
  const counts=(await c.query("SELECT count(*)::int AS retained,count(*) FILTER(WHERE status='pending')::int AS pending,count(*) FILTER(WHERE status='pending' AND owner_id IS NOT DISTINCT FROM $1::uuid)::int AS owned FROM community_images",[owner])).rows[0];
  if(counts.retained>=LIMITS.retained||counts.pending>=LIMITS.pendingGlobal||counts.owned>=LIMITS.pendingPerGuest)throw new CommunityError('The submission queue is full. Please try later.',429);
  await c.query("DELETE FROM community_submission_days WHERE day < (now() AT TIME ZONE 'UTC')::date - 1");
  for(const [key,limit] of [['global',LIMITS.dailyGlobal],[owner??'admin',LIMITS.dailyPerGuest]] as const){const result=await c.query("INSERT INTO community_submission_days(day,owner_key,count) VALUES((now() AT TIME ZONE 'UTC')::date,$1,1) ON CONFLICT(day,owner_key) DO UPDATE SET count=community_submission_days.count+1 WHERE community_submission_days.count<$2 RETURNING count",[key,limit]);if(!result.rowCount)throw new CommunityError('Daily submission limit reached.',429);}
  return submission((await c.query(`INSERT INTO community_images(id,owner_id,title,credit,image,width,height) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING ${columns}`,[randomUUID(),owner,title,credit,image,width,height])).rows[0]);
 });}
 async moderate(id:string,patch:{status?:'approved'|'rejected';featured?:boolean;sortOrder?:number}){return this.economy.transaction(async c=>{await this.lock(c);const row=(await c.query(`UPDATE community_images SET status=COALESCE($2,status),featured=COALESCE($3,featured),sort_order=COALESCE($4,sort_order),moderated_at=now() WHERE id=$1 RETURNING ${columns}`,[id,patch.status??null,patch.featured??null,patch.sortOrder??null])).rows[0];if(!row)throw new CommunityError('Image unavailable',404);await c.query('INSERT INTO community_moderation(image_id,action) VALUES($1,$2)',[id,JSON.stringify(patch)]);await this.bump(c);return submission(row);});}
 async remove(id:string){await this.economy.transaction(async c=>{await this.lock(c);if(!(await c.query('DELETE FROM community_images WHERE id=$1',[id])).rowCount)throw new CommunityError('Image unavailable',404);await c.query("INSERT INTO community_moderation(image_id,action) VALUES($1,'deleted')",[id]);await this.bump(c);});}
 async update(settings:ProgrammeSettings,expectedRevision:number){return this.economy.transaction(async c=>{await this.lock(c);const result=await c.query('UPDATE community_programme SET mode=$1,platform=$2,twitch_channel=$3,youtube_video_id=$4,schedule=$5::jsonb,revision=revision+1,epoch=clock_timestamp() WHERE singleton AND revision=$6 RETURNING revision',[settings.mode,settings.platform,settings.twitchChannel,settings.youtubeVideoId,JSON.stringify(settings.schedule),expectedRevision]);if(!result.rowCount)throw new CommunityError('Programme changed. Refresh before saving.',409);return this.snapshot(c);});}
}
