import assert from 'node:assert/strict';
import test from 'node:test';
import sharp from 'sharp';
import { normalizeCommunityImage,validateProgramme } from '../server/community.ts';
import { CommunityAdminSessions,hashCommunityPassword,verifyCommunityPassword,RequestLimiter } from '../server/communityAuth.ts';
import { communitySlide,communityImages,BRIDGEMIND_TWITCH_CHANNEL,type Programme } from '../shared/community.ts';
test('community passwords, fixed session expiry, revocation and bounded limiter',async()=>{const hash=await hashCommunityPassword('a long test password');assert.equal(await verifyCommunityPassword('a long test password',hash),true);assert.equal(await verifyCommunityPassword('wrong',hash),false);assert.equal(await verifyCommunityPassword('wrong',''),false);const sessions=new CommunityAdminSessions(),token=sessions.create(100),cookie=sessions.cookie(token,true);assert.match(cookie,/HttpOnly; SameSite=Strict/);assert.match(cookie,/Secure/);assert.ok(sessions.valid(cookie,101));assert.equal(sessions.valid(cookie,100+sessions.ttl),false);const newer=sessions.cookie(sessions.create(),false);sessions.revoke(newer);assert.equal(sessions.valid(newer),false);const limiter=new RequestLimiter(1,100,1);assert.ok(limiter.take('a',0));assert.equal(limiter.take('a',1),false);assert.equal(limiter.take('b',1),false);assert.ok(limiter.take('b',101));});
test('community decodes still images, strips metadata, rejects SVG/corrupt/oversize',async()=>{const input=await sharp({create:{width:2000,height:1200,channels:3,background:'red'}}).jpeg().withMetadata().toBuffer();const result=await normalizeCommunityImage(input.toString('base64'));assert.equal(result.width,1800);assert.equal(result.height,1080);const meta=await sharp(result.data).metadata();assert.equal(meta.format,'webp');assert.equal(meta.exif,undefined);for(const input of ['invalid','x'.repeat(6*1024*1024),Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"></svg>').toString('base64')])await assert.rejects(normalizeCommunityImage(input));const png=await sharp({create:{width:1,height:1,channels:3,background:'red'}}).png().toBuffer();const animationChunk=Buffer.alloc(20);animationChunk.writeUInt32BE(8,0);animationChunk.write('acTL',4);animationChunk.writeUInt32BE(2,8);await assert.rejects(normalizeCommunityImage(Buffer.concat([png.subarray(0,33),animationChunk,png.subarray(33)]).toString('base64')));const huge=await sharp({create:{width:4000,height:4000,channels:3,background:'red'}}).png().toBuffer();await assert.rejects(normalizeCommunityImage(huge.toString('base64')));});
test('programme validates manually curated identifiers and advances shared slides',()=>{const settings={mode:'intermission',platform:'twitch',twitchChannel:BRIDGEMIND_TWITCH_CHANNEL,youtubeVideoId:'',schedule:[]};assert.equal(validateProgramme(settings).twitchChannel,BRIDGEMIND_TWITCH_CHANNEL);assert.throws(()=>validateProgramme({...settings,twitchChannel:'https://evil.test'}));assert.throws(()=>validateProgramme({...settings,schedule:[{id:'a',title:'Stream',platform:'twitch',startsAt:'tomorrow'}]}));const p={...settings,revision:1,epochMs:100,serverNowMs:100,images:communityImages([])} as Programme;assert.equal(communitySlide(p,100).kind,'image');assert.equal(communitySlide(p,20100).kind,'schedule');assert.equal(communitySlide(p,40100).kind,'image');assert.equal(communitySlide({...p,mode:'live'}).kind,'live');});

test("programme fixes Twitch to BridgeMind and normalizes case",()=>{const settings={mode:"live",platform:"twitch",twitchChannel:"BridgeMindAI",youtubeVideoId:"",schedule:[]};assert.equal(validateProgramme(settings).twitchChannel,BRIDGEMIND_TWITCH_CHANNEL);assert.throws(()=>validateProgramme({...settings,twitchChannel:"anotherchannel"}));assert.equal(validateProgramme({...settings,platform:"youtube",youtubeVideoId:"abcdefghijk"}).youtubeVideoId,"abcdefghijk");});
