import {webkit} from 'playwright';import{writeFile}from'node:fs/promises';
const browser=await webkit.launch({headless:true}),results=[];
try{for(const dpr of[1,3]){const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:dpr,hasTouch:true});await page.goto('http://localhost:5173');await page.getByRole('button',{name:'Choose your look',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector<HTMLButtonElement>('.enter')?.disabled);await page.waitForTimeout(1000);
await page.evaluate(async()=>{const path='/node_modules/.vite/deps/@babylonjs_core_Engines_engine.js';const{Engine}=await import(path);(window as any).probeEngine=Engine.Instances[0]});
const measure=()=>page.evaluate(()=>{const c=document.querySelector('canvas')!,engine=(window as any).probeEngine,cam=engine.scenes[0].activeCamera;return{dpr:devicePixelRatio,inner:[innerWidth,innerHeight],css:[c.clientWidth,c.clientHeight],buffer:[c.width,c.height],engine:[engine.getRenderWidth(),engine.getRenderHeight()],scale:engine.getHardwareScalingLevel(),viewport:JSON.stringify(cam.viewport)};});
const before=await measure();await page.evaluate(()=>window.dispatchEvent(new Event('resize')));await page.waitForTimeout(500);const after=await measure();
await page.getByRole('textbox',{name:'What should we call you?'}).fill('Mobile review');await page.getByRole('button',{name:'Choose your look',exact:true}).click();await page.getByRole('button',{name:'Join the square',exact:true}).waitFor();await page.waitForTimeout(700);await page.screenshot({path:`output/playwright/polish/11-mobile-customisation-dpr${dpr}.png`});const preview=await measure();
await page.getByRole('button',{name:'Join the square',exact:true}).click();await page.getByRole('button',{name:'Open town map'}).waitFor();await page.waitForTimeout(4500);await page.getByRole('button',{name:'Toggle town chat'}).click();
const overlap=await page.evaluate(()=>{const input=document.querySelector<HTMLInputElement>('input[aria-label="Message to town"]')!,rect=input.getBoundingClientRect(),x=rect.x+rect.width*.3,y=rect.y+rect.height/2,hit=document.elementFromPoint(x,y);return{inputRect:rect.toJSON(),point:[x,y],hit:hit?.className,hitTag:hit?.tagName,insideJoystick:!!hit?.closest('.joystick')};});await page.screenshot({path:`output/playwright/polish/12-mobile-town-dpr${dpr}.png`});results.push({dpr,before,after,preview,overlap});await page.close();}await writeFile('output/playwright/polish/mobile-probe.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));}finally{await browser.close();}
