import {webkit} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('output/playwright/polish',{recursive:true});
const browser=await webkit.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:960},hasTouch:true});page.setDefaultTimeout(30000);
const report:Record<string,unknown>={checkedAt:new Date().toISOString(),browser:'headless WebKit; device emulation is not native performance'},errors:string[]=[];
page.on('pageerror',e=>errors.push(e.message));
const shot=async(name:string)=>{await page.waitForTimeout(450);return page.screenshot({path:`output/playwright/polish/${name}.png`});};
const camera=()=>page.evaluate(()=>{const s=(window as any).auditScene,c=s.activeCamera;return{alpha:c.alpha,beta:c.beta,radius:c.radius,lowerRadiusLimit:c.lowerRadiusLimit,renderWidth:s.getEngine().getRenderWidth(),renderHeight:s.getEngine().getRenderHeight(),scaling:s.getEngine().getHardwareScalingLevel(),shadows:s.shadowsEnabled};});
const attach=()=>page.evaluate(async()=>{const path='/node_modules/.vite/deps/@babylonjs_core_Engines_engine.js';const{Engine}=await import(path);(window as any).auditScene=Engine.Instances[0].scenes[0];});
const smallControls=()=>page.evaluate(()=>[...document.querySelectorAll<HTMLElement>('button,input,select,summary')].filter(el=>el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden').map(el=>({name:el.getAttribute('aria-label')||el.getAttribute('title')||el.textContent?.trim().slice(0,65),width:Math.round(el.getBoundingClientRect().width),height:Math.round(el.getBoundingClientRect().height)})).filter(el=>el.width<44||el.height<44));
async function position(){await page.getByRole('button',{name:'Open town map'}).click();const m=page.locator('.town-map circle[fill="#253d33"]');const p={x:Number(await m.getAttribute('cx')),z:-Number(await m.getAttribute('cy'))};await page.getByRole('button',{name:'Close panel'}).click();return p;}
async function walk(axis:'x'|'z',target:number){for(let i=0;i<22;i++){const delta=target-(await position())[axis];if(Math.abs(delta)<.28)return;await page.locator('#world').focus();const key=axis==='x'?(delta>0?'d':'a'):(delta>0?'w':'s');await page.keyboard.down(key);await page.waitForTimeout(Math.min(1300,Math.max(65,Math.abs(delta)/4.2*1000)));await page.keyboard.up(key);await page.waitForTimeout(150);}throw Error(`Walk blocked at ${axis}=${target}`);}
async function flush(){report.errors=errors;await writeFile('output/playwright/polish/audit.json',JSON.stringify(report,null,2));}
try{
 await page.goto('http://localhost:5173');await page.getByRole('textbox',{name:'WHAT SHOULD WE CALL YOU?'}).fill('Polish review');await page.getByRole('button',{name:'Enter',exact:true}).click();await page.getByRole('button',{name:'Join the square',exact:true}).waitFor();await attach();
 await page.setViewportSize({width:390,height:844});report.customiseSmallControls=await smallControls();await shot('01-mobile-customisation');await page.setViewportSize({width:1440,height:960});await page.getByRole('button',{name:'Join the square',exact:true}).click();await page.getByRole('button',{name:'Open town map'}).waitFor();const welcome=page.getByRole('button',{name:'Dismiss welcome'});if(await welcome.isVisible())await welcome.click();await page.waitForTimeout(1000);
 report.startCamera=await camera();await shot('02-town-desktop');
 await page.setViewportSize({width:390,height:844});report.townSmallControls=await smallControls();await shot('03-town-mobile');await page.setViewportSize({width:844,height:390});await shot('04-town-landscape');await page.setViewportSize({width:1440,height:960});
 await page.getByRole('button',{name:'Open settings'}).click();await page.getByRole('checkbox',{name:/Performance mode/}).check();await page.getByRole('button',{name:'Close panel'}).click();report.lowQualityBeforeWardrobe=await camera();
 await page.getByRole('button',{name:'Open wardrobe'}).click();await page.getByRole('button',{name:'Close wardrobe'}).waitFor();await page.getByRole('button',{name:'Close wardrobe'}).click();report.afterWardrobe=await camera();
 await page.getByRole('button',{name:'Open settings'}).click();await page.getByRole('checkbox',{name:/Performance mode/}).uncheck();await page.getByRole('button',{name:'Close panel'}).click();
 await walk('x',-4.7);await walk('z',11.2);await walk('x',0);await walk('z',16.5);report.beforeFacadeCollision=await camera();await walk('x',-3.8);report.atFacadeCollision=await camera();await shot('05-camera-by-facade');
 await page.locator('#world').focus();await page.keyboard.down('s');await page.waitForTimeout(1700);
 report.blockedWalk=await page.evaluate(()=>{const s=(window as any).auditScene;return{groups:s.animationGroups.filter((g:any)=>g.isPlaying).map((g:any)=>g.name),cameraRadius:s.activeCamera.radius};});await shot('06-walking-into-wall');await page.keyboard.up('s');
 await walk('z',16.5);await walk('x',0);await walk('z',11.2);report.afterReturningOutside=await camera();await shot('07-camera-after-exit');
 await page.getByRole('button',{name:'Recenter camera'}).click();await walk('z',16.5);await walk('z',22.2);await walk('x',.5);report.nearbyGames=await page.locator('.casino-entry').innerText();await page.setViewportSize({width:390,height:844});await shot('08-nearby-games-mobile');await page.setViewportSize({width:1440,height:960});
 await page.getByRole('button',{name:'Open Meridian reels · 3',exact:true}).click();report.slotCamera=await camera();await shot('09-slot-idle-desktop');await page.getByRole('button',{name:'Close casino table'}).click();
 await page.getByRole('button',{name:'Open settings'}).click();await page.getByRole('checkbox',{name:/Performance mode/}).check();await page.reload();await page.getByRole('button',{name:'Enter',exact:true}).click();await page.getByRole('button',{name:'Join the square',exact:true}).click();await page.getByRole('button',{name:'Open settings'}).click();report.performanceModeAfterReload=await page.getByRole('checkbox',{name:/Performance mode/}).isChecked();
 await flush();console.log('World, camera, mobile and settings observations captured.');
 const highDpi=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:3,hasTouch:true});await highDpi.goto('http://localhost:5173');await highDpi.getByRole('button',{name:'Enter',exact:true}).waitFor();await highDpi.waitForFunction(()=>!document.querySelector<HTMLButtonElement>('.enter')?.disabled);
 report.highDpi=await highDpi.evaluate(()=>{const c=document.querySelector('canvas')!;return{dpr:devicePixelRatio,cssWidth:c.clientWidth,bufferWidth:c.width,cssHeight:c.clientHeight,bufferHeight:c.height};});await highDpi.screenshot({path:'output/playwright/polish/10-high-dpi-phone.png'});await highDpi.close();await flush();console.log(JSON.stringify(report,null,2));
}catch(error){report.failure=String(error);await flush();await shot('failure').catch(()=>{});throw error;}finally{await browser.close();}
