import assert from 'node:assert/strict';
import { loadEnvFile } from 'node:process';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { GuestRepository } from '../server/persistence/guests.ts';
import { EconomyRepository, EconomyError } from '../server/persistence/economy.ts';
import { CasinoRepository } from '../server/persistence/casino.ts';
import { SocialRepository } from '../server/persistence/social.ts';
loadEnvFile('.env');
assert.ok(['localhost','127.0.0.1','[::1]'].includes(new URL(process.env.DATABASE_URL!).hostname),'Use the local development database only');
const admin=new Pool({connectionString:process.env.DATABASE_URL});
const schema=`social_test_${randomUUID().replaceAll('-','')}`;
const url=new URL(process.env.DATABASE_URL!);url.searchParams.set('options',`-c search_path=${schema}`);
const guests=new GuestRepository(url.toString());const economy=new EconomyRepository(guests.pool);let social=new SocialRepository(economy);
const reject=(code:string)=>(e:unknown)=>e instanceof EconomyError&&e.code===code;
try{
 await admin.query(`CREATE SCHEMA ${schema}`);await guests.initialise();await economy.initialise();await new CasinoRepository(economy).initialise();
 const a=(await guests.create({name:'Alice',shirt:0,skin:0})).profile.id,b=(await guests.create({name:'Bob',shirt:0,skin:0})).profile.id;
 const epoch=randomUUID();await economy.openSession(a,epoch);await economy.checkpoint(a,epoch,600000);
 await social.initialise();await guests.initialise();await economy.initialise();await new CasinoRepository(economy).initialise();await social.initialise();
 assert.equal((await social.snapshot(a)).giftingAllowance,0,'historical salary grants no allowance');
 await assert.rejects(social.gift(a,b,1,randomUUID(),()=>true),reject('insufficient_allowance'));
 await economy.checkpoint(a,epoch,1200000);await economy.checkpoint(a,epoch,1200000);
 assert.equal((await social.snapshot(a)).giftingAllowance,100);
 const request=randomUUID();const receipts=await Promise.all(Array.from({length:5},()=>social.gift(a,b,20,request,()=>true)));
 assert.equal(receipts.filter(r=>!r.replayed).length,1);assert.equal((await social.snapshot(a)).giftingAllowance,80);
 assert.equal((await social.snapshot(b)).giftingAllowance,0,'incoming gift cannot be laundered');
 await assert.rejects(social.gift(b,a,1,randomUUID(),()=>true),reject('insufficient_allowance'));
 assert.equal((await social.gift(a,b,20,request,()=>false)).replayed,true);
 await assert.rejects(social.gift(a,b,21,request,()=>true),reject('request_conflict'));
 await assert.rejects(social.gift(a,a,1,randomUUID(),()=>true),reject('invalid_target'));
 for(const amount of [0,-1,0.5,1001,NaN])await assert.rejects(social.gift(a,b,amount,randomUUID(),()=>true),reject('invalid_gift'));
 const before=await economy.ensure(a);await assert.rejects(social.gift(a,b,20,randomUUID(),()=>false),reject('not_nearby'));assert.deepEqual(await economy.ensure(a),before);
 await Promise.all([social.gift(a,b,30,randomUUID(),()=>true),economy.purchase(a,'oat-knit','social-purchase')]);
 assert.equal((await social.snapshot(a)).giftingAllowance,50);
 const epochB=randomUUID();await economy.openSession(b,epochB);await economy.checkpoint(b,epochB,600000);
 const sumBefore=(await economy.ensure(a)).balance+(await economy.ensure(b)).balance;
 await Promise.all([social.gift(a,b,10,randomUUID(),()=>true),social.gift(b,a,10,randomUUID(),()=>true)]);
 assert.equal((await economy.ensure(a)).balance+(await economy.ensure(b)).balance,sumBefore);
 const c=(await guests.create({name:'Cara',shirt:0,skin:0})).profile.id;
 await assert.rejects(social.gift(a,c,20,request,()=>true),reject('request_conflict'));
 const requests=await Promise.allSettled([social.friend(a,b,'request'),social.friend(b,a,'request')]);
 assert.equal(requests.filter(r=>r.status==='fulfilled').length,1);assert.equal((await social.snapshot(a)).friends.length,0);
 const pending=await social.snapshot(a);await social.friend(pending.incoming.length?a:b,pending.incoming.length?b:a,'accept');
 assert.equal((await social.snapshot(a,()=>true)).friends[0].online,true);
 await guests.setBlock(b,a,true);assert.equal((await social.snapshot(a)).friends.length,0);
 await assert.rejects(social.gift(a,b,1,randomUUID(),()=>true),reject('blocked'));await assert.rejects(social.friend(a,b,'request'),reject('blocked'));
 assert.equal((await social.gift(a,b,20,request,()=>false)).replayed,true);
 await guests.setBlock(b,a,false);await social.friend(a,b,'remove');assert.equal((await social.snapshot(b)).friends.length,0);
 await social.friend(a,b,'request');await social.friend(a,b,'cancel');assert.equal((await social.snapshot(b)).incoming.length,0);
 await social.friend(a,b,'request');await social.friend(b,a,'decline');assert.equal((await social.snapshot(a)).outgoing.length,0);
 await assert.rejects(social.friend(a,a,'request'),reject('invalid_target'));
 // Force a late ledger failure to prove both wallets and receipt roll back together.
 await guests.pool.query("ALTER TABLE economy_ledger ADD CONSTRAINT test_reject_gift CHECK(kind<>'gift_sent') NOT VALID");
 const stateA=await economy.ensure(a),stateB=await economy.ensure(b),allowance=(await social.snapshot(a)).giftingAllowance,failed=randomUUID();
 await assert.rejects(social.gift(a,b,1,failed,()=>true));assert.deepEqual(await economy.ensure(a),stateA);assert.deepEqual(await economy.ensure(b),stateB);assert.equal((await social.snapshot(a)).giftingAllowance,allowance);
 await guests.pool.query('ALTER TABLE economy_ledger DROP CONSTRAINT test_reject_gift');await social.gift(a,b,1,failed,()=>true);
 const other=new Pool({connectionString:url.toString()});try{social=new SocialRepository(new EconomyRepository(other));await social.initialise();assert.equal((await social.gift(a,b,1,failed,()=>false)).replayed,true);}finally{await other.end();}
 assert.equal((await guests.pool.query("SELECT sum(amount)::int AS total FROM economy_ledger WHERE kind IN ('gift_sent','gift_received')")).rows[0].total,0);
 console.log('PASS: isolated social migration/restart, nonretroactive salary allowance, grant/incoming laundering prevention, concurrent gift/purchase and reciprocal gifts, retry/conflict/offline replay, bounds/self/proximity/block, friend transitions/concurrency, and atomic rollback/paired ledger.');
}finally{await guests.close();await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin.end();}
